[features]
seeds = false
skip-lint = false
[programs.devnet]
lptoken = "Dbt4xEW1CJyAxuegXs9bo5hs9qtXsE9eobJEU1bPNZsp"
sushiswap = "9mkw5Vx1as4GPeufggiCkzy1EB71hkAJDJTC3mpqZUUQ"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/hardik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
